catinder/config/routes.rb
Rails.application.routes.draw do
  # Root/home page
  root 'cats#welcome'
  # Show all cats
  get 'cats/' => 'cats#index'
  # Render page to create new cat
  get 'cats/new' => 'cats#new', as: :new_cat
  # Show single cat
  get 'cats/:id' => 'cats#show', as: :cat
  # Action to create new cat
  post 'cats/' => 'cats#create'
  # Render page to edit cat
  get 'cats/:id/edit' => 'cats#edit', as: :edit_cat
  # Action to update/edit cat
  patch 'cats/:id' => 'cats#update'
  # Action to delete/destroy cat
  delete 'cats/:id' => 'cats#destroy'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

catinder/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

catinder/app/models/cat.rb
class Cat < ApplicationRecord
end

catinder/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

catinder/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def welcome
    # render welcome page
  end

  # Render page with ALL cats
  def index
    @cats = Cat.all
  end

  # Render individual cat page
  def show
    @cat = Cat.find(params[:id])
  end

  # Render page to create NEW cat
  def new
    @cat = Cat.new
  end

  #Action to create new cat
  def create
    @cat = Cat.new(params.require(:cat).permit(:name, :image_uri, :votes))

    if @cat.save
      redirect_to cats_path
    else
      render :new
    end
  end

  # Render edit page for specific cat
  def edit
    @cat = Cat.find(params[:id])
  end

  # Action to update/edit specific cat
  def update
    @cat = Cat.find(params[:id])

    if @cat.update_attributes(params.require(:cat).permit(:name, :image_uri, :votes))
      redirect_to cat_path
    else
      render :edit
    end
  end

  # Action to delte/destroy specific cat
  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy
    redirect_to cats_path
  end
end

catinder/app/helpers/application_helper.rb
module ApplicationHelper
end

catinder/app/helpers/cats_helper.rb
module CatsHelper
end

catinder/app/views/cats/create.html.erb
<h1>Cats#create</h1>
<p>Find me in app/views/cats/create.html.erb</p>

catinder/app/views/cats/delete.html.erb
<h1>Cats#delete</h1>
<p>Find me in app/views/cats/delete.html.erb</p>

catinder/app/views/cats/edit.html.erb
<div class="container">
<h1>Edit <%= @cat.name %> </h1>

<%= form_for @cat do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name%>
    </div>
    
    <div>
        <%= f.label :image_uri %>
        <%= f.text_field :image_uri %>
    </div>

    <%= f.submit "Add New Cat!" %>

<% end %>

</div>

catinder/app/views/cats/index.html.erb
<div class="container">
<h1>List of Cats:</h1>

    <% @cats.each do |c| %>
        <%= image_tag (c.image_uri) %>
        <h3><a href="/cats/<%= c.id %>"><%= c.name %></a></h4>
        <p> Votes: <%= c.votes %> </p>
        
    <% end %>
</div>

catinder/app/views/cats/new.html.erb
<h1>Add a New Cat</h1>

<%= form_for @cat do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name%>
    </div>
    
    <div>
        <%= f.label :image_uri %>
        <%= f.text_field :image_uri %>
    </div>

    <%= f.submit "Add New Cat!" %>

<% end %>

catinder/app/views/cats/show.html.erb
<div class="container">
<h1>Cat: <%= @cat.name %></h1>

<%= image_tag (@cat.image_uri) %>
<p> Number of votes: <%= @cat.votes %> </p>


<%= link_to "Edit this cat", edit_cat_path(@cat) %>  |
<%= link_to "Delete this cat!", :cat, method: :delete, data: { confirm: "Are you sure you want to delete this cat?"} %>
</div>

catinder/app/views/cats/update.html.erb
<h1>Cats#update</h1>
<p>Find me in app/views/cats/update.html.erb</p>

catinder/app/views/cats/welcome.html.erb
<div class="container">
<%= image_tag ("catinder-logo.png") %>

<h1>Welcome to CaTinder!</h1>

<h3>Pets start here.</h3>

<p>Who is Meow, and who is Not-Meow? You decide!</p>

<a href="/cats?random=true">Get started</a>

</div>

catinder/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catinder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/navbar' %>
    <%= yield %>
  </body>
</html>

catinder/app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/cats?random=true">Catinder</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
            <a class="nav-link" href="/">Catinder Home</a>
            </li>
            <li class="nav-item active">
            <a class="nav-link" href="/cats">Cat Index <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="/cats/new">New Cat</a>
            </li>
            
        </ul>
    </div>
</nav>